{{- $cert_manager_used := and (not (and .Values.tls.crt .Values.tls.key)) (eq .Values.tls.generateCerts.executor "cert-manager") }}
{{- if and $cert_manager_used (not .Values.tls.generateCerts.clusterIssuerName) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: site-manager-tls-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
